[package]
name = "help"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { workspace = true, features = ["cuda"] }
cuda-runtime-sys = "0.3.0-alpha.1"
half = { version = "2.4.1", features = ["num-traits"] }
